In [1]:
# Numpy 

In [2]:
import numpy as np

In [3]:
lst = [1,2,3,4]
arr = np.array(lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(4,)

In [6]:
arr1 = np.array([[1,2,3],[4,5,6]])
# 2 dimentions
arr1.shape

(2, 3)

In [7]:
print(arr1.reshape(3,2))
print()
print(arr1.reshape(1,6))
print()
print(arr1.reshape(6,1))
# arr1.reshape(3,3) will give error

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3 4 5 6]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [8]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [9]:
np.array({'yash':'dahekar','meow':'khan'})
print(np.array({'yash':'dahekar','meow':'khan'}).reshape(1,1))

[[{'yash': 'dahekar', 'meow': 'khan'}]]


In [10]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr1.dtype

dtype('int32')

In [12]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [14]:
np.arange(1,10,2).shape

(5,)

In [15]:
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [16]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [17]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [19]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [20]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [21]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [22]:
np.linspace(1,20,40)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [23]:
np.linspace(1,20,40).shape

(40,)

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [28]:
5 + np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [29]:
np.eye(4) #identy matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
print('random number generation(uniform distribution)')
np.random.rand(2,3)

random number generation(uniform distribution)


array([[0.2584301 , 0.99463597, 0.60009215],
       [0.42854147, 0.46964608, 0.88144453]])

In [31]:
print('random number following a normal distribution with mean=0 and std=1')
print(np.random.randn(5,3))

random number following a normal distribution with mean=0 and std=1
[[ 1.20499873 -0.88456237 -0.94438214]
 [ 0.31167814 -0.46718493  0.86034037]
 [ 1.60318874 -0.35655099  0.70469211]
 [ 0.29272526 -1.29532718  0.05045896]
 [ 0.39238615  1.39753374 -0.49057211]]


In [32]:
np.random.randint(1,100,10)

array([91, 11, 88, 55, 14, 98, 18, 84, 25, 68])

In [33]:
np.random.randint(1,100,(4,4))

array([[81, 69, 21, 63],
       [54, 73, 29, 28],
       [54, 71, 90, 37],
       [97, 31, 67, 97]])

In [34]:
arr = np.arange(0,11)

In [35]:
# Slicing
arr[2:7]

array([2, 3, 4, 5, 6])

In [36]:
arr1 = np.random.randint(2,100,20).reshape(5,4)

In [37]:
arr1

array([[52, 55, 35, 35],
       [77, 63, 79, 78],
       [83, 74, 61, 49],
       [15, 58, 60, 92],
       [ 6, 49, 54, 42]])

In [38]:
arr1[:3,:3]

array([[52, 55, 35],
       [77, 63, 79],
       [83, 74, 61]])

In [39]:
arr1[2:4,[0,-1]] #import and assigment

array([[83, 49],
       [15, 92]])

In [40]:
#universal functions 
arr1 = np.random.randint(1,100,(3,3))
arr2 = np.random.randint(1,100,(3,3))
print(arr1, '\n''\n', arr2)


[[84 61  7]
 [62 19 12]
 [19 13 67]] 

 [[88 30 28]
 [63 66 74]
 [31 56 18]]


In [41]:
arr1 + arr2

array([[172,  91,  35],
       [125,  85,  86],
       [ 50,  69,  85]])

In [42]:
arr1 - arr2

array([[ -4,  31, -21],
       [ -1, -47, -62],
       [-12, -43,  49]])

In [43]:
arr1 * arr2

array([[7392, 1830,  196],
       [3906, 1254,  888],
       [ 589,  728, 1206]])

In [44]:
arr1 / arr2

array([[0.95454545, 2.03333333, 0.25      ],
       [0.98412698, 0.28787879, 0.16216216],
       [0.61290323, 0.23214286, 3.72222222]])

In [45]:
np.sqrt(arr1)

array([[9.16515139, 7.81024968, 2.64575131],
       [7.87400787, 4.35889894, 3.46410162],
       [4.35889894, 3.60555128, 8.18535277]])

In [46]:
np.exp(arr2)

array([[1.65163625e+38, 1.06864746e+13, 1.44625706e+12],
       [2.29378316e+27, 4.60718663e+28, 1.37338298e+32],
       [2.90488497e+13, 2.09165950e+24, 6.56599691e+07]])

In [47]:
np.log10(arr1)

array([[1.92427929, 1.78532984, 0.84509804],
       [1.79239169, 1.2787536 , 1.07918125],
       [1.2787536 , 1.11394335, 1.8260748 ]])

In [48]:
arr1 = np.arange(1,10)

In [49]:
arr1[2:] = 1000

In [50]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

: 